version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tarek-taha-website
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # If you need environment variables
    # environment:
    #   - REACT_APP_API_URL=https://api.example.com
    # For persistent storage if needed
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
